name: Keep Codespace Alive
on:
  schedule:
    - cron: "*/15 * * * *"  # Runs every 15 minutes
jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: Start Codespace
        run: |
          gh codespace create -r ${{ github.repository }}
